var fruits = ['Apples', 'Oranges', 'Lemons', 'Pears', 'Pineapples'];
var vegetables = ['Carrot', 'Lettuce', 'Tomato', 'Potato', 'Onion'];
var fruitsVegetables = [
  {
    key: 'Fruits',
    items: fruits,
  },
  {
    key: 'Vegetables',
    items: vegetables,
  },
];
var doingTasks = [
  { id: 1, text: 'Prepare 2019 Financial' },
  { id: 2, text: 'Prepare 2019 Marketing Plan' },
  { id: 3, text: 'Update Personnel Files' },
  {
    id: 4,
    text: 'Review Health Insurance Options Under the Affordable Care Act',
  },
];

var products = [
  {
    ID: 1,
    Name: 'HD Video Player',
    Price: 330,
    Current_Inventory: 225,
    Backorder: 0,
    Manufacturing: 10,
    Category: 'Video Players',
    ImageSrc: 'images/products/1.png',
  },
  {
    ID: 3,
    Name: 'SuperPlasma 50',
    Price: 2400,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/3.png',
  },
  {
    ID: 4,
    Name: 'SuperLED 50',
    Price: 1600,
    Current_Inventory: 77,
    Backorder: 0,
    Manufacturing: 55,
    Category: 'Televisions',
    ImageSrc: 'images/products/4.png',
  },
  {
    ID: 5,
    Name: 'SuperLED 42',
    Price: 1450,
    Current_Inventory: 445,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/5.png',
  },
  {
    ID: 6,
    Name: 'SuperLCD 55',
    Price: 1350,
    Current_Inventory: 345,
    Backorder: 0,
    Manufacturing: 5,
    Category: 'Televisions',
    ImageSrc: 'images/products/6.png',
  },
  {
    ID: 7,
    Name: 'SuperLCD 42',
    Price: 1200,
    Current_Inventory: 210,
    Backorder: 0,
    Manufacturing: 20,
    Category: 'Televisions',
    ImageSrc: 'images/products/7.png',
  },
  {
    ID: 8,
    Name: 'SuperPlasma 65',
    Price: 3500,
    Current_Inventory: 0,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Televisions',
    ImageSrc: 'images/products/8.png',
  },
  {
    ID: 9,
    Name: 'SuperLCD 70',
    Price: 4000,
    Current_Inventory: 95,
    Backorder: 0,
    Manufacturing: 5,
    Category: 'Televisions',
    ImageSrc: 'images/products/9.png',
  },
  {
    ID: 10,
    Name: 'DesktopLED 21',
    Price: 175,
    Current_Inventory: null,
    Backorder: 425,
    Manufacturing: 75,
    Category: 'Monitors',
    ImageSrc: 'images/products/10.png',
  },
  {
    ID: 12,
    Name: 'DesktopLCD 21',
    Price: 170,
    Current_Inventory: 210,
    Backorder: 0,
    Manufacturing: 60,
    Category: 'Monitors',
    ImageSrc: 'images/products/12.png',
  },
  {
    ID: 13,
    Name: 'DesktopLCD 19',
    Price: 160,
    Current_Inventory: 150,
    Backorder: 0,
    Manufacturing: 210,
    Category: 'Monitors',
    ImageSrc: 'images/products/13.png',
  },
  {
    ID: 14,
    Name: 'Projector Plus',
    Price: 550,
    Current_Inventory: null,
    Backorder: 55,
    Manufacturing: 10,
    Category: 'Projectors',
    ImageSrc: 'images/products/14.png',
  },
  {
    ID: 15,
    Name: 'Projector PlusHD',
    Price: 750,
    Current_Inventory: 110,
    Backorder: 0,
    Manufacturing: 90,
    Category: 'Projectors',
    ImageSrc: 'images/products/15.png',
  },
  {
    ID: 17,
    Name: 'ExcelRemote IR',
    Price: 150,
    Current_Inventory: 650,
    Backorder: 0,
    Manufacturing: 190,
    Category: 'Automation',
    ImageSrc: 'images/products/17.png',
  },
  {
    ID: 18,
    Name: 'ExcelRemote BT',
    Price: 180,
    Current_Inventory: 310,
    Backorder: 0,
    Manufacturing: 0,
    Category: 'Automation',
    ImageSrc: 'images/products/18.png',
  },
  {
    ID: 19,
    Name: 'ExcelRemote IP',
    Price: 200,
    Current_Inventory: 0,
    Backorder: 325,
    Manufacturing: 225,
    Category: 'Automation',
    ImageSrc: 'images/products/19.png',
  },
];
var plannedTasks = [
  { id: 5, text: 'New Brochures' },
  { id: 6, text: '2019 Brochure Designs' },
  { id: 7, text: 'Brochure Design Review' },
  { id: 8, text: 'Website Re-Design Plan' },
  { id: 9, text: 'Rollout of New Website and Marketing Brochures' },
  { id: 10, text: 'Create 2018 Sales Report' },
  { id: 11, text: 'Direct vs Online Sales Comparison Report' },
  { id: 12, text: 'Review 2018 Sales Report and Approve 2019 Plans' },
  { id: 13, text: 'Submit Signed NDA' },
  { id: 14, text: 'Update Revenue Projections' },
  { id: 15, text: 'Review Revenue Projections' },
  { id: 16, text: 'Comment on Revenue Projections' },
  { id: 17, text: 'Scan Health Insurance Forms' },
  { id: 18, text: 'Sign Health Insurance Forms' },
  { id: 19, text: 'Follow up with West Coast Stores' },
  { id: 20, text: 'Follow up with East Coast Stores' },
  { id: 21, text: 'Submit Refund Report for 2019 Recall' },
  { id: 22, text: 'Give Final Approval for Refunds' },
  { id: 23, text: 'Prepare Product Recall Report' },
  { id: 24, text: 'Review Product Recall Report by Engineering Team' },
  { id: 25, text: 'Review Training Course for any Ommissions' },
  { id: 26, text: 'Review Overtime Report' },
  { id: 27, text: 'Submit Overtime Request Forms' },
  { id: 28, text: 'Overtime Approval Guidelines' },
  { id: 29, text: 'Create Report on Customer Feedback' },
  { id: 30, text: 'Review Customer Feedback Report' },
];
